### ISSUE TITLE
Question: How to match "chars until a string"?

### ISSUE THREAD

**Issue by Magicloud** [d-plaindoux/celma#10]
For example, bash variable substitution. The input is written as `"This is ${prog_name} speaking"`. In my opinion, it should be parsed into something like `[PLAIN("This is "), VAR("prog_name"), PLAIN(" speaking")]`. But when I write the plain parser, I could not figure out how to "consume any chars until string '${'".

**Comment by d-plaindoux** [comment]
My first solution should be:
```rust
lookahead(string('$').and_right(char('{'))).or(any()).rep()
```

But the current `lookup` implementation does not return a consumed stream. As a consequence, this parser never finishes i.e. undecidable.

**Comment by Magicloud** [comment]
Thanks. This is different than my design (I have a working parser in Haskell by Parsec). Maybe I should rethink it in another way.

**Comment by d-plaindoux** [comment]
Did you have a fragment showing the difference with the Haskell approach? How the lookahead is managed in such a case?

**Comment by d-plaindoux** [comment]
This can be "simple" done using parsers like:
```rust
#[derive(Debug, Clone, PartialEq)]
enum Expr {
    Text(String),
    Var(String),
    Seq(Vec<Expr>)
}

fn mk_string(a: Vec<char>) -> String {
    a.into_iter().collect::<String>()
}

parsec_rules!(
    let bash:{Expr} = s=(text | var)*       -> {Expr::Seq(s)}
    let text:{Expr} = t=^('$' '{')+         -> {Expr::Text(mk_string(t))}
    let var:{Expr}  = ('$' '{' v=^'}'* '}') -> {Expr::Var(mk_string(v))}
);
```

**Comment by d-plaindoux** [comment]
The `not` parser has been generalized (See #14). The previous example can be written as follow:
```rust
parsec_rules!(
    let bash:{Expr} = s=(text | var)*    -> {Expr::Seq(s)}
    let text:{Expr} = t=^"${"+           -> {Expr::Text(mk_string(t))}
    let var:{Expr}  = ("${" v=^'}'* '}') -> {Expr::Var(mk_string(v))}
)
```

The `text` is also the parser: `string("${").not().rep()`

**Comment by Magicloud** [comment]
With the changed mentioned in the last comment, I think I can close the issue. Thanks.
