### ISSUE TITLE
Escaping issue.

### ISSUE THREAD

**Issue by Magicloud** [d-plaindoux/celma#16]
First of all, I do not know if this is Celma issue, or just how proc macro works.

When I make parsec_rules, I write `'\"'` in code. Then use `cargo expand`. The expanded code contains `'\"'` as expected.

But when I write `"\""`, the expanded code is `"\\\""`.

**Comment by d-plaindoux** [comment]
This is probably a problem in the string delimiter parser implementation. I'll check it.

**Comment by d-plaindoux** [comment]
In fact the parser `"\""` means an escaped `"`. So for instance in a JSON fragment we can write:
```json
"a simple \" string  \" "
```
When we parse this string we should be able to identify `\` and `"`. This is why we have `"\\\"` in the Rust source code.

**Comment by Magicloud** [comment]
If this is handled here as a raw string, how could I specify a string contains only a double quote sign?

For example, `^("${" | "\"")`

**Comment by d-plaindoux** [comment]
That's right. So I will check again the implementation and the related tests.
