### ISSUE TITLE
What do `alter`s mean?

### ISSUE THREAD

**Issue by Magicloud** [d-plaindoux/celma#5]
First of all, thanks for the work. Especially the macro, really making char to char consuming more clear (meaningful).

While I was reading the README, one thing I did not quite get. What do those alters mean?

I guess `^` means "not any", `!` means "not all". But I have no idea what does `#` mean.

**Comment by d-plaindoux** [comment]
I review the README and I try to explain the meaning of each alteration. Feel free to comment.

**Comment by Magicloud** [comment]
Thanks. I just got some ideas from reading the source.
