### ISSUE TITLE
How to do "look ahead"?

### ISSUE THREAD

**Issue by Magicloud** [d-plaindoux/celma#6]
For example, in this parsec rule `let STRING:{String}      = ('"' c=#((("\"" -> {'\"'})|^'"')*) '"') -> {mk_string(c)}`, I assuming that it consumes the whole string of `"something"`. If I want to stop when next char is double quote, but leave it in the stream?

**Comment by d-plaindoux** [comment]
For the moment the lookahead does not exist in the core base code. So I/we must first design it in the base and later it should be added in the macro-based language. For this purpose, I created issue #7. Feel free to comment.

**Comment by Magicloud** [comment]
Thanks.
